### ISSUE TITLE
poleEndPoint.getVelocity returns six NAN

### ISSUE THREAD

**Issue by JadarTheObscurity** [aidudezzz/deepbots-tutorials#4] opened 2020-09-19 23:45 UTC
I followed the tutorial but I don't know why did poleEndPoint.getVelocity returns NAN.

**Comment by tsampazk** [comment] 2020-09-20 10:56
Hello @JadarTheObscurity.

Unfortunately i can't reproduce the issue. Can you provide any additional information? E.g. what Webots version are you using?

Could you perhaps run the [complete example](https://github.com/aidudezzz/deepbots-tutorials/tree/master/cartPoleTutorial/full_project) as provided with the tutorial and see if you get the same issue?

**Comment by JadarTheObscurity** [comment] 2020-09-20 12:03
I've tried the the complete example and get the same result.
The value of cartPosition, cartVelocity and poleAngle are all fine, I think
the problem is at "self.supervisor.getFromDef("POLE_ENDPOINT")", which did
not return the right Solid we want, but I don't know how to test whether it
returns a Solid  or not.

Here are the information I can think of:
Windows 10 x64
Python 3.7.9
Webots R2020b


Kostas Tsampazis <notifications@github.com> 於 2020年9月20日 週日 下午6:56寫道：

**Comment by tsampazk** [comment] 2020-09-20 12:23
It seems weird because when i run the full example as-is it runs fine for me.

-  Firstly, the only difference of the system information you shared is the Webots version. So, i would suggest downloading the latest revision of [Webots version R2020b-rev1](https://cyberbotics.com/#download) in case some bug was introduced in version R2020 and fixed in the revision, before trying anything else.

Other than that, to investigate the issue check out the following:

- If `self.supervisor.getFromDef("POLE_ENDPOINT")` doesn't find the DEF, it returns `None` so you will get a different error message (something along the lines of `None doesn't have the method getVelocity`)
- We can rule out `getFromDef` getting some other node other than POLE_ENDPOINT, but you can try adding a `print(self.poleEndpoint)` after line 15 in the constructor, to get some information about what it actually returns
- You can check the robot definition and find the POLE_ENDPOINT node to check whether it is properly defined. It should be as follows in [CartPoleRobot.wbo file under the SupervisorController directory, on line 148](https://github.com/aidudezzz/deepbots-tutorials/blob/7f2937373d4c3ff697139191536ab145ae205f4a/cartPoleTutorial/full_project/controllers/supervisorController/CartPoleRobot.wbo#L148-L167).

**Comment by JadarTheObscurity** [comment] 2020-09-20 15:42
I've updated Webot to the newest version and it works! Thanks for your help!
By the way, are you planning adding how to save/load the model in the
tutorial? It will be very helpful if we can save the model that works.


Kostas Tsampazis <notifications@github.com> 於 2020年9月20日 週日 下午8:23寫道：

**Comment by tsampazk** [comment] 2020-09-20 16:04
That's great, happy to help!

We tried to keep the tutorial code as simple as possible, but that could be an additional short tutorial that can be incorporated into the repository in the future.

Until then you can use the [save and load](https://github.com/aidudezzz/deepbots-tutorials/blob/7f2937373d4c3ff697139191536ab145ae205f4a/cartPoleTutorial/full_project/controllers/supervisorController/PPOAgent.py#L93-L111) methods included in the provided PPO agent and implement your own save/loading functionality.

Feel free to ask any additional questions, cheers!

**Closed by tsampazk** 2020-09-20 16:04 UTC

**Comment by tsampazk** [comment] 2021-02-17 10:57
@all-contributors please add @JadarTheObscurity for ideas
